// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2M0ZDHMt9muMUBsBRGF8AAJmz2F4r8bA',
    appId: '1:203210975455:web:cb2381695e783e04c6e16a',
    messagingSenderId: '203210975455',
    projectId: 'persist-wallet-app',
    authDomain: 'persist-wallet-app.firebaseapp.com',
    storageBucket: 'persist-wallet-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTbyVtmQePahJwaLNuD1xLcKGHFehd0OI',
    appId: '1:203210975455:android:76bfadd8d240491bc6e16a',
    messagingSenderId: '203210975455',
    projectId: 'persist-wallet-app',
    storageBucket: 'persist-wallet-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6_bxPUMt8zpU88lQ1k2JenPSFpKdVe0U',
    appId: '1:203210975455:ios:734d48ac9bedd9a9c6e16a',
    messagingSenderId: '203210975455',
    projectId: 'persist-wallet-app',
    storageBucket: 'persist-wallet-app.appspot.com',
    iosBundleId: 'com.example.persistWalletApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2M0ZDHMt9muMUBsBRGF8AAJmz2F4r8bA',
    appId: '1:203210975455:web:50c9cdc0d87832dac6e16a',
    messagingSenderId: '203210975455',
    projectId: 'persist-wallet-app',
    authDomain: 'persist-wallet-app.firebaseapp.com',
    storageBucket: 'persist-wallet-app.appspot.com',
  );
}
